3DReconstructionFrom2D:
    leftImagePath: "data/2viewSFM/0014_2.png"
    rightImagePath: "data/2viewSFM/0017_2.png"
    focalLength: 552
    u0: 307.5
    v0: 205
    outputDirectory: "output/2viewSFM/"

OpticalFlow:
    dataDirectory: "data/opticalflow/"
    threshold: 10
    plotFlow: True
    findEpipoles: True
    computeDepth: True
    computePlanarFlow: True